### ISSUE TITLE
PhotoをRegionでTumblrにポストしようとするとエラーになる。

### ISSUE THREAD

**Issue by array** [tombfix/core#150]
表題の通りです。
エラーメッセージは以下の通り。
ポストエラー
  Tumblr: 
      
      result : 2147500037
      line : 1004
      columnNumber : 0
      location : utility.js

環境は
Firefox 35 beta
Tombfix　0.1.15

普通にPhotoをそのままポストすることは可能です。

**Comment by syoichi** [comment]
問題を報告して頂きありがとうございます! 問題の発生を確認いたしました。
Firefox 35.0 で File Constructor に変更があったようですね。

**Comment by syoichi** [comment]
バージョン[0.1.6](http://syoichi.tumblr.com/post/107843460910)で対応しました。

**Comment by array** [comment]
ありがとうございました。
