### ISSUE TITLE
Tumblrに投稿できない

### ISSUE THREAD

**Issue by array** [tombfix/core#161]
以下のエラーで投稿ができません。
ポストエラー
  Tumblr: 
      file : utility.js
      line : 1911
      columnNumber : 5
      src is null

元ページ: 
  コミュニティ | Mozilla Japan
  http://www.mozilla.jp/community/
Tombfixのバージョン　0.2.3
Firefoxのバージョン　Firefox 36 Beta（本日更新が来ました）
OS　Windows8.1 64bit
新規プロファイルでの状況　新規プロファイル

以上です。

**Comment by syoichi** [comment]
問題の報告ありがとうございます!
Firefox 35.0.1でも問題の発生を確認しました。Tumblrで仕様変更があったようです。
#157 と同じく、「アカウントの切り替え」は動作しているようですね。

**Comment by syoichi** [comment]
バージョン[0.2.4](http://syoichi.tumblr.com/post/110790876310)で対応しました。
