### ISSUE TITLE
Photo - pixivでポストエラー

### ISSUE THREAD

**Issue by eru** [tombfix/core#186]
2015/05/11にpixivのspapiが廃止された影響で、`fixImageExtensionFromAPI`を通るパターンでリクエストのレスポンスが404のため正常に動作せず、下記のエラーが表示されます。

```
ポストエラー
  file : extractors.js
  line : 1473
  columnNumber : 14
  [object Object]
```

対応として、[新APIがあります](https://danbooru.donmai.us/wiki_pages/58938)が、API呼び出しの認証過程でIDとPWを使用するため、pixivのID、PWをオプションとして追加して保持するなどの対応が必要となるかと思います。

**Comment by syoichi** [comment]
問題を報告して頂きありがとうございます!
このエラーは数日前に確認していたのですが、調査不足で原因を把握しておりませんでした。なるほど、仕様変更の影響でしたか…。

色々と調査しなければなりませんが、ひとまずこの問題への対応は、現在蓄積されている変更を含んだ新バージョンを今後数日以内にリリースしてから行いたいと思います。

>API呼び出しの認証過程でIDとPWを使用するため、pixivのID、PWをオプションとして追加して保持するなどの対応が必要となるかと思います。

新APIについてはまだ確認していませんが、ユーザーがFirefoxのパスワードマネージャでアカウント情報を管理していれば、[`getPasswords()`](https://github.com/tombfix/core/blob/a95733fac5aabbed5c906b234cb84d4e77fef6bf/xpi/chrome/content/library/utility.js#L333-344)でアカウント情報は取得できるので、これに関する新たな設定の追加は必要ないかもしれませんね。

**Comment by syoichi** [comment]
この問題の修正の目処はほぼ立ったのですが、Regressionが存在しないかなどの確認に時間がかかりそうなので、先に #194 の修正を含んだバージョンのリリースを優先させます。

**Comment by syoichi** [comment]
バージョン[0.3.5](http://syoichi.tumblr.com/post/120072735325)で修正しました。
修正を含んだバージョンをリリースするまでに不具合の報告を頂いてから2週間も時間がかかってしまい大変申し訳ありませんでした…。

**Comment by eru** [comment]
お疲れ様でした。ありがとうございます！
