### ISSUE TITLE
can't post any photos to twitter 

### ISSUE THREAD

**Issue by junrxu** [tombfix/core#195]
![111](https://cloud.githubusercontent.com/assets/3841679/7773361/9f86b50c-00d6-11e5-85f7-25120eeb42b9.png)

**Comment by syoichi** [comment]
Thanks for the bug report! But, this issue is duplicate of #194.
And, this issue is fixed in Tombfix 0.3.4(1bc1ce25355cc90048d0b6730bd931091cdcd2ac). Please update.
