### ISSUE TITLE
不具合報告：Pixiv画像をアップする際にポストエラーが出ます。

### ISSUE THREAD

**Issue by HatoHato** [tombfix/core#200]
syoichi様
いつもtombfixを使わせて頂き、大変感謝しております。
Pixivの画像をTumblrにアップする時にポストエラーのダイアログが出てしまうので、報告させて頂きます。

■ダイアログ内容
ポストエラー
  file : extractors.js
  line : 1806
  columnNumber : 16
  コンテンツが見つかりません。

元ページ: 
  (2) 「むねっしー」/「児玉酉」のイラスト [pixiv]
  http://www.pixiv.net/member_illust.php?mode=medium&illust_id=36825401

ページを開き直しますか？

投稿する画像でエラーが出るものと出ないものがあるようです。
元ページの画像はエラーが出たものをお借りしました。
ご対応頂ければ幸いです。

※追加　情報を書き忘れていました。申し訳ございません。
・Tombfix のバージョン
0.3.5

・Firefox のバージョン
38.0.5

・OS
Windows7 HomePremium SP1 64bit 

・Tombfix のみがインストールされた新規プロファイルでも不具合が発生するか
発生しました。

・Tombfix を再インストールしても不具合が発生するか
発生しました。

・インストールしているパッチ
ありません。

・サードパーティ Cookie を拒否しているか(参考 1、参考 2)
常に許可状態

インストールしている拡張機能(アドオン)
McAfee Security Scan Plus 1.0（無効）
セキュリティキーボード　14.0.0.4971（無効）
ネット決済保護 14.0.0.4971（無効）
バナー広告対策 14.0.0.4971(無効)
危険サイト診断 14.0.0.4971(無効)

宜しくお願い致します。

**Comment by syoichi** [comment]
問題を報告して頂きありがとうございます!
こちらでも同様の環境で検証してみたのですが、残念ながら問題を再現できませんでした。
問題の状況を出来る限り把握する為に、以下の項目に関して情報を提供して頂ければありがたいです。

1. 問題は現在でも発生しているのでしょうか?
発生しているとなると、pixiv側の一時的な障害という原因ではなさそうですね。

2. ログアウト時でも問題は発生していますか?
ページタイトルを見たところ、ログインしている時のもののようですね。こちらでは、ログイン、ログアウト時のいずれでも問題の発生を確認できていないのですが、HatoHatoさんの環境において、ログアウト時では問題が発生しないようであれば、pixivのアカウントの設定で何らかの変化が発生しているのかもしれません。

3. 可能であれば、問題が発生しないページをお教え下さい

**Comment by HatoHato** [comment]
syoichi様
お世話になっております。

本日Tombfixにてpixiv画像をTumblrに３０件ほどpostしたところ問題なく動作しました。
以前は日を置いてもポストエラーが発生していたのですが、新規プロファイルやTombfixの再インストールをしたあと、ＰＣごと立ち上げなおしたのが影響したのかもしれません。
お騒がせして真に申し訳ありません。
ご丁寧なご対応でとても感謝しております。
ありがとうございました。

**Comment by syoichi** [comment]
特に問題が無いようで良かったです。また何かありましたらお知らせください。
