### ISSUE TITLE
Tombfixは拡張機能の署名必須化に対応すべき

### ISSUE THREAD

**Issue by array** [tombfix/core#201]
Mozillaの方針でAdd-onがSignedになっていないと使えなくなりますが、これはご対応の予定はあるのでしょうか？

**Comment by syoichi** [comment]
ご心配をお掛けして申し訳ありません。
Tombfixで対応可能かどうか試験的にaddons.mozilla.orgへの登録作業をするなどして調査をしているのですが、大規模な実装の変更を必要とする可能性があることがわかってきています。
1つ確かなのは、**現状の実装のままでは**Tombfixをaddons.mozilla.orgに登録することはできず、いずれTombfixはFirefoxの最新の安定版では使用不能になってしまうということです。

次のリリース時にTombfixの拡張機能の署名必須化への対応に関して言及したいと思っております。

**Comment by array** [comment]
期待しております。ありがとうございました。

**Comment by syoichi** [comment]
[Tombfixにおける拡張機能の署名必須化への対応について](http://syoichi.tumblr.com/post/128620630290)書きました。

**Comment by syoichi** [comment]
バージョン[0.4.0](http://syoichi.tumblr.com/post/128980870070)で対応しました。
