### ISSUE TITLE
「Photo - pixiv」Extractor: マンガ形式で原寸大の画像が取得できない

### ISSUE THREAD

**Issue by eru** [tombfix/core#202]
ここ1週間くらいの間で仕様変更？か何かがあったようで、img-originalの画像がないマンガ形式の投稿が存在するようです。

`http://www.pixiv.net/member_illust.php?mode=medium&illust_id=52404505` の1枚目の画像であれば、従来であれば、`http://i2.pixiv.net/img-original/img/2015/09/07/00/02/01/52404505_p0.jpg`というURLになっていましたが、ログイン状態でアクセスしても404となってしまいます。

おそらく、アドオン自体には特に影響はないと思いますが念のため。

**Comment by syoichi** [comment]
ブラウザコンソールでリクエストの状況を見てみましたが、恐らくその挙動は予期されたものですね。
「Photo - pixiv」Extractorでは基本的に`mode=medium`のページから情報を取得し、サムネイルの画像の拡張子を使ってオリジナルの画像のURLと推測されるものを生成しリクエストしています。1回でオリジナルの画像が取得できなければ、[`IMG_EXTENSIONS`](https://github.com/tombfix/core/blob/720d704bdd20b979b31271649256eec1710cb8fd/xpi/chrome/content/library/extractors.js#L1346)に従って拡張子を変えて取得できないかどうかを試します。
例として挙げられている[作品ページ](http://www.pixiv.net/member_illust.php?mode=medium&illust_id=52404505)のサムネイルの画像の拡張子は`jpg`です。`jpg`が駄目なら次に取得するのは`png`になるのでここで[オリジナルの画像](http://i2.pixiv.net/img-original/img/2015/09/07/00/02/01/52404505_p0.png)が取得できているようですね。

![screenshot](https://cloud.githubusercontent.com/assets/69238/9726808/ce725c66-5632-11e5-8693-64c139b98e0a.png)

この挙動はイラスト形式の[この作品ページ](http://www.pixiv.net/member_illust.php?mode=medium&illust_id=47411037)でも確認することができます。
