### ISSUE TITLE
Photo captureのRegionが機能しない

### ISSUE THREAD

**Issue by kingtosh** [tombfix/core#203]
コンテクストメニューから、Share>Photo capture>Regionを選択して、選択範囲を作成するためにマウスをドラッグすると、マウスカーソルは＋に変わるのですがテキストやその他の要素が選択されてしまって、キャプチャーの選択範囲が作成されません。Region以外は機能してます。

FF41
tombfix0.3.6、0.4.0、0.4.1
Mac OS X 10.8.5

**Comment by syoichi** [comment]
[Tombfixの対応環境](https://github.com/tombfix/core#%E5%AF%BE%E5%BF%9C%E7%92%B0%E5%A2%83)上で、Firefox 41.0の新規プロファイルにTombfix 0.4.1をインストールして、[このページ](https://tombfix.github.io/)で確認したところ特に問題はありませんでした。

![screenshot](https://cloud.githubusercontent.com/assets/69238/10126002/99145340-65c2-11e5-8015-13618e7f6f04.png)

よろしければ、どのページで問題が発生しているかお教えください。

**Comment by kingtosh** [comment]
すいません、こちらの環境のせいでした。ユーザースクリプトの一つが干渉していました。それを外したら、問題なく動作しました。

**Comment by syoichi** [comment]
特に問題が無いようで良かったです。また何かありましたらお知らせください。
