### ISSUE TITLE
Reblog関連のExtractorが一部のページで動作しなくなってる

### ISSUE THREAD

**Issue by syoichi** [tombfix/core#204]
[quinoco](https://twitter.com/quinoco/status/672260724668821504)さんや[nise_3kawan](https://twitter.com/nise_3kawan/status/672369388880719872)さんのツイートより。Message関連の変更で、ユーザーサイトで表示されるReblogボタンなどが入ったiframeが変化したことが原因かな?

「ReBlog - Dashboard」Extractorや「ReBlog - Tumblr link」Extractor、「ReBlog - LDR」ExtractorでTumblrのコンテンツを取得しようとすると、以下の様なエラーが表示される。
![screenshot](https://cloud.githubusercontent.com/assets/69238/11608071/d5af3d9a-9ba2-11e5-8459-518078de91a0.png)

一方、「ReBlog - Tumblr」Extractorに至ってはコンテキストメニューに表示さえされない状態になっている。

**Comment by ktrotns** [comment]
http://goo.gl/5nQdDq
参考になりますでしょうか。

**Comment by syoichi** [comment]
情報ありがとうございます! [リンク先](http://man-nona.tumblr.com/post/134508895846)の現象はこちらでも確認することができました。現在の状況を把握するのに役立ちます!

**Comment by syoichi** [comment]
例
* 動作するページ: http://niwaringo.tumblr.com/post/111470925699
* 動作しないページ: http://staff.tumblr.com/post/134552569330

**Comment by taizooo** [comment]
* 動作するページ: http://niwaringo.tumblr.com/post/111470925699
 * https://www.tumblr.com/dashboard/iframe?tumblelogName=staff&singlePostId=134552569330
* 動作しないページ: http://staff.tumblr.com/post/134552569330
 * https://www.tumblr.com/dashboard/iframe?src=http%3A%2F%2Fniwaringo.tumblr.com%2Fpost%2F111470925699%2Ftumblr%25E3%2581%25AE%25E6%2596%25B0%25E3%2581%2597%25E3%2581%2584%25E3%2582%25A8%25E3%2583%25AA%25E3%2582%25A2%25E3%2581%25AA%25E3%2582%2593%25E3%2581%258B%25E3%2582%25B9%25E3%2582%25B4%25E3%2582%25A4%25E7%2584%25A1%25E9%25A7%2584%25E3%2581%25AB%25E3%2581%2597%25E3%2582%2588%25E3%2581%2586%25E3%2581%25A8%25E3%2581%2597%25E3%2581%25A6%25E3%2581%258F%25E3%2582%258C%25E3%2581%25A6%25E3%2581%2584%25E3%2582%258B%25E3%2581%258C%25E3%2582%25AD%25E3%2583%25BC%25E3%2583%259C%25E3%2583%25BC%25E3%2583%2589%25E3%2582%25B7%25E3%2583%25A7%25E3%2583%25BC%25E3%2583%2588%25E3%2582%25AB%25E3%2583%2583%25E3%2583%2588%25E3%2581%258C%25E5%258A%25B9%25E3%2581%258B&pid=111470925699&rk=M0PY7rkc&lang=ja_JP&name=niwaringo&avatar=http%3A%2F%2F33.media.tumblr.com%2Favatar_602bbe70cdd2_64.png&title=niwaringo%28%29+%7BTumblr%7D&url=http%3A%2F%2Fniwaringo.tumblr.com%2F&page_slide=slide&_v=d6db350c287d0f6886d738d3d844fe81

へー、2種類あるんですね。

**Comment by syoichi** [comment]
あっ、その2つのiframeのURL、逆になってますね。正しくは長い方が動作するページのものです。

見ての通り、動作しない方のiframeのURLは短すぎてTombfixが解釈するには情報が足りません。今まではユーザーサイトのページのiframeのURLだけからReblogに必要な情報を得られていたのですが、新しい動作しない方に将来的には統一されるのだとすると、何か別のなるべく将来に渡って安定して情報を得られる方法を探さないといけないのです。

**Comment by taizooo** [comment]
* 動作するページ: http://niwaringo.tumblr.com/post/111470925699
* https://www.tumblr.com/dashboard/iframe?src=http%3A%2F%2Fniwaringo.tumblr.com%2Fpost%2F111470925699%2Ftumblr%25E3%2581%25AE%25E6%2596%25B0%25E3%2581%2597%25E3%2581%2584%25E3%2582%25A8%25E3%2583%25AA%25E3%2582%25A2%25E3%2581%25AA%25E3%2582%2593%25E3%2581%258B%25E3%2582%25B9%25E3%2582%25B4%25E3%2582%25A4%25E7%2584%25A1%25E9%25A7%2584%25E3%2581%25AB%25E3%2581%2597%25E3%2582%2588%25E3%2581%2586%25E3%2581%25A8%25E3%2581%2597%25E3%2581%25A6%25E3%2581%258F%25E3%2582%258C%25E3%2581%25A6%25E3%2581%2584%25E3%2582%258B%25E3%2581%258C%25E3%2582%25AD%25E3%2583%25BC%25E3%2583%259C%25E3%2583%25BC%25E3%2583%2589%25E3%2582%25B7%25E3%2583%25A7%25E3%2583%25BC%25E3%2583%2588%25E3%2582%25AB%25E3%2583%2583%25E3%2583%2588%25E3%2581%258C%25E5%258A%25B9%25E3%2581%258B&pid=111470925699&rk=M0PY7rkc&lang=ja_JP&name=niwaringo&avatar=http%3A%2F%2F33.media.tumblr.com%2Favatar_602bbe70cdd2_64.png&title=niwaringo%28%29+%7BTumblr%7D&url=http%3A%2F%2Fniwaringo.tumblr.com%2F&page_slide=slide&_v=d6db350c287d0f6886d738d3d844fe81
* 動作しないページ: http://staff.tumblr.com/post/134552569330
 * https://www.tumblr.com/dashboard/iframe?tumblelogName=staff&singlePostId=134552569330

 こうですね。間違えました!

iframe の url から reblog の url を組み立てるんでしたっけ?

**Comment by syoichi** [comment]
はい。該当箇所は以下の辺りですね。
* [Extractors.ReBlog.getFrameUrl()](https://github.com/tombfix/core/blob/1a71964ccc0558789c23b64ff5f5f1b582b79550/xpi/chrome/content/library/extractors.js#L644-L657)
* [Extractors.ReBlog.extractByPage()](https://github.com/tombfix/core/blob/1a71964ccc0558789c23b64ff5f5f1b582b79550/xpi/chrome/content/library/extractors.js#L623-L626)

**Comment by taizooo** [comment]
iframe の url の先のページの構造も new と old では違うんですけど reblog のボタンの url の構成は同じですね。

* 動作するページの iframe の先の reblog url
 * /reblog/111470925699/M0PY7rkc?redirect_to=http%3A%2F%2Fniwaringo.tumblr.com%2Fpost%2F111470925699%2Ftumblr%25E3%2581%25AE%25E6%2596%25B0%25E3%2581%2597%25E3%2581%2584%25E3%2582%25A8%25E3%2583%25AA%25E3%2582%25A2%25E3%2581%25AA%25E3%2582%2593%25E3%2581%258B%25E3%2582%25B9%25E3%2582%25B4%25E3%2582%25A4%25E7%2584%25A1%25E9%25A7%2584%25E3%2581%25AB%25E3%2581%2597%25E3%2582%2588%25E3%2581%2586%25E3%2581%25A8%25E3%2581%2597%25E3%2581%25A6%25E3%2581%258F%25E3%2582%258C%25E3%2581%25A6%25E3%2581%2584%25E3%2582%258B%25E3%2581%258C%25E3%2582%25AD%25E3%2583%25BC%25E3%2583%259C%25E3%2583%25BC%25E3%2583%2589%25E3%2582%25B7%25E3%2583%25A7%25E3%2583%25BC%25E3%2583%2588%25E3%2582%25AB%25E3%2583%2583%25E3%2583%2588%25E3%2581%258C%25E5%258A%25B9%25E3%2581%258B&source=iframe

* 動作しないページの iframe の先の reblog url
 * https://www.tumblr.com/reblog/134552569330/m1Hu782q/?redirect_to=http%3A%2F%2Fstaff.tumblr.com%2Fpost%2F134552569330

ttps://www.tumblr.com/reblog/134552569330//reblog/{data-key}/?redirect_to={url}

ほー、 iframe の url だけじゃ足りないってことはもしかして一度 iframe の url の先のページを取ってこないとダメってことですか。

**Comment by syoichi** [comment]
その方法でも解決できるかもしれないですが、他のもっと別のより良い方法が無いか考えているところです。理想的にはReblog IDだけで何とかしたいのです。
具体的には #120 で示したAPIが活用できればと思っています。

**Comment by taizooo** [comment]
ほほう、 API ですかー。期待しています!!!

**Comment by polygonplanet** [comment]
非同期を同期する必要がありますが、
[getFrameUrlの最後のほう](https://github.com/tombfix/core/blob/1a71964ccc0558789c23b64ff5f5f1b582b79550/xpi/chrome/content/library/extractors.js#L655-L656) を
```javascript
      src = (src || '').replace(/\\x22/g, '"').replace(/\\x26/g, '&');

      if (!src) {
        var m = doc.URL.match(/https?:\/\/([^.]+)\.tumblr\.com\/post\/([^\/]+)/);
        if (m) {
          var sync = false;

          request('https://www.tumblr.com/dashboard/iframe', {
            queryString : {
              tumblelogName : m[1],
              singlePostId : m[2]
            }
          }).addCallback(res => {
            src = res.responseText.extract(/"reblogUrl":"(.*?)"/, 1).replace(/\\\//g, '/');
            sync = true;
          });

          // 同期
          till(() => sync);
        }
      }
      return src;
```

こんな感じにして、
[extractByPage](https://github.com/tombfix/core/blob/1a71964ccc0558789c23b64ff5f5f1b582b79550/xpi/chrome/content/library/extractors.js#L623-L626)も
```javascript
    extractByPage : function(ctx, doc){
      var url = this.getFrameUrl(doc);
      var m = unescapeHTML(url).match(/.+&pid=([^&]*)&rk=([^&]*)/);
      if (m) {
        url = Tumblr.TUMBLR_URL+'reblog/' + m[1] + '/' + m[2];
      }
      return this.extractByEndpoint(ctx, url);
    },
```
合わせて直して、
あまりテストしてませんが、これでとりあえず動きました。

**Comment by syoichi** [comment]
おおー、実装の提案をして頂きありがとうございます! これはtaizoooさんが示された方法の具体案な感じですね。
この実装ですと、#120 よりはTumblrのサイトであるかの最初の判定はより精度が高そうですが、残念ながら、`till()`は以下のようにAMO側で危険な処理として判定されるコードを含んでいる為(`eval()`などとは違い警告だけで済むのでアドオンの署名は得られます)、将来のことを考えると、あまり好ましくはありませんね。#120 で示した方法などのより良い解決策がうまく形にできなかった時の最終手段として考えてみたいと思います。

![screenshot](https://cloud.githubusercontent.com/assets/69238/11610543/8df1ad2a-9be9-11e5-8429-4b76bc0206e9.png)

**Comment by polygonplanet** [comment]
'ReBlog - Tumblr' の `check` で `getFrameUrl` を使わないようにできたらよさそうですね

**Comment by ailispaw** [comment]
Taberareloo 的には暫定的にこんな感じにしてみました。
https://gist.github.com/ailispaw/a1934684cdee9a10506a

**Comment by syoichi** [comment]
ありがとうございます! なるほど、Tumblr API v1を活用する形ですね。Reblog Keyを得るための情報量としてはTumblr API v2とあまり変わらず、また、独自ドメインでも問題ないようですね。
しかし、これはあまり現実的ではない可能性かもしれませんが、Tumblrの独自ドメインのユーザーサイトを装った攻撃サイト上でExtractorを実行した場合などを考慮すると、幾ばくか不安が残るんですよね…。
故に、`api.tumblr.com`のようなTumblr自身が管理しているサービスに、このサイトが本当にTumblrのユーザーサイトなのかを直接問い合わせるような形の方がより安全性が高いと判断し、現在、#205 でTumblr API v2を活用して実装を試みています。

**Comment by syoichi** [comment]
@polygonplanet 今回の仕様変更に対応する、TumblrのReblogに関する実装の刷新の仕様がほぼ確定し、`Extractors.ReBlog.extractByEndpoint()`を削除することが決定しました。
影響を受けるパッチは[tombloo.extractor.tumblr.highres.js](https://github.com/polygonplanet/tombloo/blob/master/tombloo.extractor.tumblr.highres.js)です。今回の変更への対応そのものは、`extractByEndpoint`を`extract`と修正するだけで可能であるはずです。
このパッチの基本的な機能は今回の変更に[含まれる](https://github.com/tombfix/core/commit/5bd7f7fea30cfa89866406382d2b8d7fd99308ad#diff-19ff06e6a382863d75768f580ee3d374R195)ことになったのですが、Photosetに関する発展的な機能は現在のTombfixには存在しないため、まだこのパッチが必要とされるケースが存在しているものと思われます。
とは言え、私には把握できていない問題があるかもしれませんので、polygonplanetさんの方で今回の変更に対応する必要があるかどうかを考えて頂けたらと思います。

**Comment by polygonplanet** [comment]
@syoichi パッチの対応までありがとうございます！
APIの場合original_size.urlだけで取得できるんですね。
[tombloo.extractor.tumblr.highres.js](https://github.com/polygonplanet/tombloo/blob/master/tombloo.extractor.tumblr.highres.js) は不要になったので、削除しようと思います。

**Comment by syoichi** [comment]
バージョン[0.5.0](http://syoichi.tumblr.com/post/135417320090)で修正しました。
